### ISSUE TITLE
Project-2 Peer Review

### ISSUE THREAD

**Issue by rish742** [INFO-526-FA24/project-2-data-nexus#1]
**Peer Review**

1. Reviewing Team: Stat Squad
•	Prasanth Gubbala(PrasanthGubbala), 
•	Prudhvi Kandregula(ksprudhvi), 
•	Xenia De Gracia(xenidegracia), 
•	Rishab RK(rish742)    

2. **_Describe the goal of the project_.**
    The goal of the project is to create a public safety awareness campaign that leverages crime data from Los Angeles (2020-present) to educate residents on crime trends, identify high-risk areas, and encourage proactive safety measures. 
    
3. **_Describe the data used or collected._**
    The project uses crime data from the LAPD, which is anonymized and updated bi-weekly. The data includes various crime types, locations, demographics, and other details relevant to crime trends.
    
4. **_Describe how the research question will be answered, e.g. what approaches / methods will be used._**
    - The primary research question is: What are the most common crime types and high-risk areas in Los Angeles? The project will use data cleaning, preprocessing, trend analysis, and visualization methods such as heatmaps and time series charts to reveal patterns. 
    - A secondary question focuses on assessing the campaign's impact on community engagement and safety awareness by comparing crime statistics pre and post-campaign.     

5. **_Is there anything that is unclear from the proposal?_**
    Aspects which remain unclear is:
    - the strategy for tailoring campaign materials and messaging to different demographic groups in Los Angeles.
    - The method for gathering and analyzing community feedback is not fully detailed. 

6. **_Provide constructive feedback on how the team might be able to improve their project._**
    - Adding a well-organized file structure would make the project easier to navigate. Consider setting up folders as given in the project 2 guidelines.
    - Consider defining specific metrics for evaluating community engagement impact beyond crime rates. For example, survey response rates, social media engagement, or attendance at community events could be useful indicators.

7. **_What aspect of this project are you most interested in and would like to see highlighted in the presentation._**
    The most intriguing aspect is the use of data visualization to identify high-risk areas and analyze crime trends over time. In the presentation, I’d recommend focusing on how the data visualizations make these crime trends accessible and actionable for residents.

8. **_Provide constructive feedback on any issues with file and/or code organization._**
    - Ensure that each folder in the repository has a README.md to explain its contents, which aligns with Project 2  guidelines for organization. 
    - Maintain consistent documentation in the code to clarify each processing and analysis step.

9. _**(Optional) Any further comments or feedback**_
     To make the campaign more impactful, consider incorporating interactive features in the visualization, like filtering by crime type or neighborhood. This could help residents better understand risks specific to their areas and adjust safety practices accordingly.     
     
Thanks & Regards,
Team - Stat Squad

**Comment by anubhavbruce** [comment]
Implemented the feedback shared by the team and closing this issue.
