### ISSUE TITLE
Peer Review by Team Insight Decoders

### ISSUE THREAD

**Issue by Hemanath17ua** [INFO-526-FA24/project-2-data-nexus#13]
Hello Team Data Nexus,

Strengths:
The plot uniquely and comprehensively visualizes the locations of crimes in LA.
The detailed mapping provides valuable insights into spatial crime patterns.

Weaknesses:
The choice of colors could be improved for better contrast and readability.
Font size and alignment issues detract from the overall visual consistency of the poster.

**Comment by nityaattili** [comment]
Feedback is taken into consideration

**Comment by anubhavbruce** [comment]
Feedback implemented!!
