### ISSUE TITLE
Project peer review by team ViZiT

### ISSUE THREAD

**Issue by anu3biswas** [INFO-526-FA24/project-2-data-nexus#2]
1.Full names and githubnames of reviewing team-
- Sree Krishnaprasad : @SreeKrishna17
- Syed Junaid Hussain : @junaidhussain22
- Anushree Biswas: @anu3biswas
- Sumel Rattan : @SumelRattan

2. Describe the goal of the project. 
To develop a public safety awareness campaign by analyzing crime data in LA from 2020 to present. To educate residents on prevalent crime types, identify high-risk areas, and promote proactive safety measures to enhance community well-being & reduce incidents.

3. Describe the data used or collected. 
Dataset used - Crime data by LAPD. 

4. Describe how the research questions will be answered, e.g what approaches/methods will be used.
Q1. Cleaning, transforming the variables like crime type, time, data & location from the crime dataset and doing trend analysis to reveal patterns over time and across neighbourhoods. They have decided to use Heatmap and a time series chart for crime types by month/year. 
Q2. Cleaning & preprocessing crime data variables like, crime incidence pre- and post-campaign, community engagement metrics. Then surveying community members on campaign awareness and perceived safety improvements. Compare crime rates in high-risk areas before and after campaign rollout. They have decided to use bar chart to compare reported crimes in key areas pre- & post-campaign. 

5. Is there anything that is unclear from the proposal ?
The description and dimensions of the data set are not visible in the proposal. 
For question 1, they talked about a time series chart for crime types. But they have not specified if it is segregated by month or year. As, it can not be both.
For question 2, they have not specified the details on the survey (mentioned in plan) they are going to conduct. It is also unclear that what survey response visualizations will be shown by the team.

6. Provide constructive feedback on how the team might be able to improve their project. 
It would be better if the team provided the data description in the form of a table.
Provide more clarity in the survey plan of the project. You can either more interactive use a clustered bar chart, slope graph, heatmap, etc. 

7. What aspect of this project are you most interested in and would like to see highlighted in the presentation?
I'd like to see more details on the community survey and use of more interactive visualizations for question 2.

8. Provide constructive feedback on any issues with file and or code organization
The team should provide the renderable .qmd proposal file, instead of a pdf proposal file.

9. Further comments and feedback. 
Overall, a good proposal, with just a few suggested improvements.

**Comment by anubhavbruce** [comment]
Implemented the feedback shared by the team and closing this issue.
