### ISSUE TITLE
Team Pixels and Patterns

### ISSUE THREAD

**Issue by sindhugoshika** [INFO-526-FA24/project-2-data-nexus#4]
Hello Team Data Nexus,

Your dataset selection is excellent, but the questions derived from it don’t seem as engaging. With only two questions, it feels like there’s not much depth to explore in your poster. I suggest adding more questions and crafting a storyline to make your presentation more compelling.

Additionally, the colors in some of your visualizations are somewhat misleading. Typically, darker colors are associated with higher values and lighter colors with lower values, but in your case, it’s different. Kindly review this to ensure clarity in your visuals.

Wishing you the best! I hope you take this feedback as a challenge to create an outstanding poster.

Team Pixels and Patterns

**Comment by anubhavbruce** [comment]
This is noted. We really appreciate your valuable feedback. We will work on adding more questions to have more storyline to the poster. Also, we will work on the color definition of the graphs so as it does not mislead.
