### ISSUE TITLE
Review from DataVizionaries

### ISSUE THREAD

**Issue by srikrish2812** [INFO-526-FA24/project-2-data-nexus#5]
Topic: Crime Data Analysis

Strength: The visualizations are eye-catching and attractive with good color choices

Weakness: The text and visualizations are not organized properly. The background blue color doesn't  seem to go well with the visualizations and seems a bit distracting to me.

**Comment by anubhavbruce** [comment]
This is noted. We will use other shades of Blue for the graphs for it not to merge with background and also try to choose a lighter background.
