### ISSUE TITLE
Review from team DataWaves

### ISSUE THREAD

**Issue by NavyasreeMadhu14** [INFO-526-FA24/project-2-data-nexus#7]
Strength: A relevant choice of data selection and clear answers to each of the questions with plots.

Weakness:  The poster background was a little overwhelming and might not appear visually appealing. Using light solid colors or gradients could be a better option for a better outlook.

**Comment by anubhavbruce** [comment]
This is noted. We will use other shades of Blue for the graphs for it not to merge with background. Also will make the background image lighter color.
