### ISSUE TITLE
review from team Dreamjobs

### ISSUE THREAD

**Issue by Lucifer970901** [INFO-526-FA24/project-2-data-nexus#8]
Ensure high contrast between the graphs and background, using accessible color gradients for better readability.
Enable viewers to hover over sections of graphs for deeper insights, such as exact values or additional context.

**Comment by anubhavbruce** [comment]
This is noted. We will use other shades of blue for the graphs for it not to merge with background. I am not sure how to hover over for the poster. But we will try to provide clearer points to get exact values.
