### ISSUE TITLE
Review by Data Detectives 

### ISSUE THREAD

**Issue by swethakolloju1** [INFO-526-FA24/project-2-data-nexus#9]
**Strength:** The dataset selection is relevant, and the visualizations are eye-catching and attract attention, with good color choices.

**Weakness:** The organization of text and visuals could be improved, as the background color is somewhat overwhelming and distracting. A more cohesive design with a lighter background could enhance the overall visual appeal.

**Comment by anubhavbruce** [comment]
This is noted. We will try use lighter background image and rearrange the text and visual to be well aligned.
